services:
  - type: web
    name: iwasscam-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    healthCheckPath: /api/v1/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://frontend-six-kappa-31.vercel.app
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: LOG_FORMAT
        value: json
      - key: CLAMAV_ENABLED
        value: "false"
      - key: USE_LLM
        value: "false"
      - key: URLHAUS_ENABLED
        value: "true"
      - key: GOOGLE_SAFE_BROWSING_API_KEY
        sync: false
    startCommand: alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 2

  - type: worker
    name: iwasscam-celery
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        fromService:
          name: iwasscam-api
          type: web
          envVarKey: SECRET_KEY
      - key: ENVIRONMENT
        value: production
      - key: USE_LLM
        value: "false"
    startCommand: celery -A app.workers.celery_app worker -Q default,heavy --loglevel=info
